default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", ENV.fetch("USER", "postgres")) %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: pcfg_shop_development

test:
  <<: *default
  database: pcfg_shop_test

production:
  <<: *default
  database: pcfg_shop_production
  url: <%= ENV["DATABASE_URL"] %>
